const RouteName = {
    SPLSH: "SplashScreen",
    SWIPER_SCREEN: "Swiperscreen",
    LOGIN_SCREEN: "LoginScreen",
    REGISTER_SCREEN: "Register",
    OTP_VERYFY_SCREEN: 'OtpVeryfiveScreen',
    HOME_SCREEN: "HomeScreen",
    REGIATRAION_SUCCESSFULL: "RegistrationSuccessful",
    HOME_TAB: 'Home',
    BOOKING_TAB: 'MyBooking',
    PAYMENT_HISTORY: 'PaymentHistory',
    PROFILE_TAB: 'Profile',
    SELECT_LANGUAGE: 'TranslationScreen',
    FORGOT_PASSSWWORD: 'ForgotPassword',
    HELP_SCREEN: 'HelpScreen',
    SETTING_SCREEN: 'SettingsScreen',
    FAQ_SCREEN: 'FAQScreen',
    REVIEWS_SCREEN: 'ReviewsScreen',
    NOTIFICTION_SCREEN: 'NotificationScreen',
    MOVIE_DETAIL_SCREEN: 'MovieDetailsScreen',
    MOVIE_BOOK_SCREEN: 'MovieBookingScreen',
    PAYMENT_SCREEN: 'PaymentScreen',
    CREDIT_CARD_SCREEN: 'CreditCardScreen',
    PAYMENT_SUCCESSFUL: 'PaymentSuccessFully',
    TICKET_SCREEN: 'TicketScreen',
}
export default RouteName;