export * from './CommonStyle';
export * from './LoginRegiesterStyle';
export * from './SwiperStyle';
export * from './TabStyles';
export * from './SettingsStyle';
export * from './HelpScreenandFAQStyles';
export * from './MovieScreenStyle';
export * from './PaymentScreenStyle';
export * from './TicketScreenStyle';