const images = {
  App_logo: require('./one_fifty.png'),
  Color_picker_image: require('./colorpicker.png'),
  First_Swiper: require('./LottieAnimation/FirstSwiper.json'),
  Two_Swiper: require('./LottieAnimation/TwoSwiper.json'),
  Three_Swiper: require('./LottieAnimation/ThreeSwiper.json'),
  Splash_Swiper: require('./LottieAnimation/SplashScreen.json'),
  Account_created: require('./LottieAnimation/Accountcreated.json'),
  Reviewsimage_screen: require('./LottieAnimation/Reviewsimage.json'),
  Languageanimation: require('./LottieAnimation/languageanimation.json'),

  Google_image: require('./googleicon.png'),
  User_image_one_profile: require('./hundred.png'),

  movie_1: require('./aladin.jpeg'),
  movie_2: require('./bloddyDaddy.jpeg'),
  movie_3: require('./dsp.jpeg'),
  movie_4: require('./fastx.jpeg'),
  movie_5: require('./major.jpeg'),
  movie_6: require('./movieReview.jpeg'),
  movie_7: require('./pathan.jpeg'),
  movie_8: require('./selfie.jpeg'),
  movie_9: require('./bhedia.jpeg'),
  movie_10: require('./shamshera.jpeg'),
  movie_11: require('./two_hundred.png'),
  movie_12: require('./selfie.jpeg'),
  movie_icon: require('./one_twenty.png'),
  Video_1: require('./two_hundred.png'),

  QR_image: require('./two_hundred.png'),

  notification_1: require('./hundred.png'),
  notification_2: require('./hundred.png'),

  paypal: require('./paypal.png'),
  Upi: require('./googlepayupilogo.png'),
  Google_pay: require('./googlepay.png'),
  freechargelogo: require('./freechargelogo.png'),
  phonepay: require('./phonepay.png'),
  Mobikwikimage: require('./Mobikwikimage.png'),
  paytem: require('./paytem.png'),
  Rupay: require('./rupayimage.png'),
  GooglePay: require('./googlepay.png'),
  PhonePay: require('./phonepay.png'),
  paypal_Icon: require('./paypal.png'),
  creditcard_img: require('./creditcardimage.png'),

  payment_successful: require('./one_fifty.png'),
  home: require('./home.png'),
  payment: require('./payment.png'),
  book: require('./book.png'),
  profile: require('./profile.png'),
};
export default images;
